### ISSUE TITLE
Issues when validating a proof

### ISSUE THREAD

**Issue by esune** [bcgov/vc-authn-oidc#268]
after proof-validation, when compiling the token to be sent back to the client, the `vc-authn-controller` throws the following error:
```
vc-authn-controller-1        | INFO:     172.27.0.1:36100 - "GET /authorize?scope=openid+vc_authn&state=-9xrbfbHh_nMDe44E30mJS0OQAo7O1wodpZw4hvxAhg.iFcXzlJMdoo.vue-fe&response_type=code&client_id=keycloak&redirect_uri=http%3A%2F%2Flocalhost%3A8880%2Fauth%2Frealms%2Fvc-authn%2Fbroker%2Fvc-authn%2Fendpoint&pres_req_conf_id=verified-email&nonce=Q2TmvV2Bl_EiSNT0gtViCw HTTP/1.1" 500 Internal Server Error
vc-authn-controller-1        | ERROR:    Exception in ASGI application
vc-authn-controller-1        | Traceback (most recent call last):
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
vc-authn-controller-1        |     result = await app(  # type: ignore[func-returns-value]
vc-authn-controller-1        |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
vc-authn-controller-1        |     return await self.app(scope, receive, send)
vc-authn-controller-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 273, in __call__
vc-authn-controller-1        |     await super().__call__(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
vc-authn-controller-1        |     await self.middleware_stack(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
vc-authn-controller-1        |     raise exc
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
vc-authn-controller-1        |     await self.app(scope, receive, _send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 84, in __call__
vc-authn-controller-1        |     await self.app(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
vc-authn-controller-1        |     raise exc
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
vc-authn-controller-1        |     await self.app(scope, receive, sender)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
vc-authn-controller-1        |     raise e
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
vc-authn-controller-1        |     await self.app(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
vc-authn-controller-1        |     await route.handle(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
vc-authn-controller-1        |     await self.app(scope, receive, send)
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
vc-authn-controller-1        |     response = await func(request)
vc-authn-controller-1        |                ^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
vc-authn-controller-1        |     raw_response = await run_endpoint_function(
vc-authn-controller-1        |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
vc-authn-controller-1        |     return await dependant.call(**values)
vc-authn-controller-1        |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/app/api/routers/oidc.py", line 59, in get_authorize
vc-authn-controller-1        |     authn_response = provider.provider.authorize(model, "vc-users")
vc-authn-controller-1        |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        |   File "/usr/local/lib/python3.11/site-packages/pyop/provider.py", line 148, in authorize
vc-authn-controller-1        |     custom_sub = self.userinfo[user_id].get('sub')
vc-authn-controller-1        |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
vc-authn-controller-1        | AttributeError: 'NoneType' object has no attribute 'get'
canceled
```

**Comment by esune** [comment]
Resolved by #269
