### ISSUE TITLE
Cannot fetch ACAPy wallet public did

### ISSUE THREAD

**Issue by kg0r0** [bcgov/vc-authn-oidc#57]
I tried Verified Credential Access from keycloaks login page.
However, the following error was displayed in the browser.
```
{"error":"acapy_call_failed","error_description":"Cannot fetch ACAPy wallet public did"}
```
I checked if ACAPy wallet is running. It didn't seem to run.
```
$ docker ps -a
CONTAINER ID        IMAGE                                                         COMMAND                  CREATED             STATUS                      PORTS                              NAMES
7d1234ca71cf        vc-authn-oidc-controller                                      "/bin/bash -c ' echo…"   14 minutes ago      Up 14 minutes               5000/tcp, 0.0.0.0:5000->80/tcp     vc-authn-oidc_controller_1
a50fa6c1dc65        bcgovimages/aries-cloudagent:py36-1.14-1_0.4.5                "/bin/bash -c 'sleep…"   14 minutes ago      Exited (0) 13 minutes ago                                      vc-authn-oidc_aca-py_1
70741c966d76        jboss/keycloak:7.0.0                                          "/opt/jboss/tools/do…"   14 minutes ago      Up 14 minutes               8443/tcp, 0.0.0.0:8180->8080/tcp   vc-authn-oidc_keycloak_1
b69ee126607c        registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest   "container-entrypoin…"   14 minutes ago      Up 14 minutes               5432/tcp                           vc-authn-oidc_keycloak-db_1
c1b7e4b3c00d        registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest   "container-entrypoin…"   14 minutes ago      Up 14 minutes               0.0.0.0:5432->5432/tcp             vc-authn-oidc_controller-db_1
f6084ab97392        registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest   "container-entrypoin…"   14 minutes ago      Up 14 minutes               0.0.0.0:5433->5432/tcp             vc-authn-oidc_wallet-db_1
```
When I checked the log, it was output as follows.
```
$ docker logs a50fa6c1dc65

. . . 

2020-03-31 06:27:57,068 aries_cloudagent.config.ledger INFO Fetching genesis transactions from: http://192.168.65.3:9000/genesis
2020-03-31 06:28:01,133 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 924, in _wrap_create_connection
    await self._loop.create_connection(*args, **kwargs))
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 794, in create_connection
    raise exceptions[0]
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/base_events.py", line 781, in create_connection
    yield from self.sock_connect(sock, address)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 439, in sock_connect
    return (yield from fut)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/asyncio/selector_events.py", line 469, in _sock_connect_cb
    raise OSError(err, 'Connect call failed %s' % (address,))
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.3', 9000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/utils/http.py", line 51, in fetch
    response: ClientResponse = await session.get(url, headers=headers)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/client.py", line 476, in _request
    timeout=real_timeout
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aiohttp/connector.py", line 931, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.65.3:9000 ssl:None [Connect call failed ('192.168.65.3', 9000)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 28, in fetch_genesis_transactions
    return await fetch(genesis_url, headers=headers)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/utils/http.py", line 59, in fetch
    raise FetchError("Exceeded maximum fetch attempts") from e
aries_cloudagent.utils.http.FetchError: Exceeded maximum fetch attempts

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 77, in init
    await startup
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/commands/start.py", line 27, in start_app
    await conductor.start()
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/core/conductor.py", line 144, in start
    await ledger_config(context, public_did)
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 43, in ledger_config
    ] = await fetch_genesis_transactions(context.settings["ledger.genesis_url"])
  File "/home/indy/.pyenv/versions/3.6.9/lib/python3.6/site-packages/aries_cloudagent/config/ledger.py", line 30, in fetch_genesis_transactions
    raise ConfigError("Error retrieving ledger genesis transactions") from e
aries_cloudagent.config.base.ConfigError: Error retrieving ledger genesis transactions

Shutting down
```
I checked the operation on macOS Catalina Version 10.15.3 .
The command I executed is:
```
$ cd docker
$ ./manage build
$ ./manage start
$ curl -X POST "http://localhost:5000/api/vc-configs" -H "accept: application/json" -H "X-Api-Key: controller-api-key" -H "Content-Type: application/json-patch+json" -d "{ \"id\": \"test-request-config\", \"subject_identifier\": \"email\", \"configuration\": { \"name\": \"Basic Proof\", \"version\": \"1.0\", \"requested_attributes\": [ { \"name\": \"email\", \"restrictions\": [] }, { \"name\": \"first_name\", \"restrictions\": [] }, { \"name\": \"last_name\", \"restrictions\": [] } ], \"requested_predicates\": [] }}"
```
Can you tell me if there are any mistakes in the steps I took?

**Comment by kg0r0** [comment]
This was my misunderstanding.

I Solved by starting VON Network.
https://github.com/bcgov/von-network#running-the-network-locally
